trigger:
- main

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Installing NodeJS V18.x'
- script: |
    npm install -g @angular/cli@14.2.9
    npm install
    ng build --configuration=production
    ng test
  displayName: 'Installing AngularCLI + npm install + build + test'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.sourcesDirectory)'
    artifact: 'dist'
    publishLocation: 'pipeline'